import { readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Generated by `sbt http4s-spa-server/meltcViteInputGenerate`.
// Maps Scala.js module IDs to their fullLinkJS output paths.
const inputsFile = resolve(__dirname, 'client/target/vite-inputs.json')
const scalaInputs = existsSync(inputsFile)
  ? JSON.parse(readFileSync(inputsFile, 'utf-8'))
  : {}

export default {
  root: __dirname,
  build: {
    manifest: true,
    outDir: resolve(__dirname, 'dist'),
    rollupOptions: {
      input: {
        ...scalaInputs,
        // Global stylesheet — emitted as a separate hashed asset so that
        // the server can resolve it via ViteManifest.fileForSourcePath().
        'styles/global': resolve(__dirname, 'styles/global.css'),
      },
    },
  },
}
