version = "3.10.7"
runner.dialect = scala3

maxColumn = 100
align.preset = more
indent.defnSite = 2
newlines.source = keep

# sbt-meltc は Scala 2.12 でコンパイルされるため、該当ファイルは scala212 dialect を使用
fileOverride {
  "glob:**/sbt-meltc/**/*.scala" {
    runner.dialect = scala212
  }
  "glob:**/project/*.scala" {
    runner.dialect = scala212
  }
}
