/**
 * Copyright (c) 2026 by Takahiko Tominaga
 * This software is licensed under the Apache License, Version 2.0 (the "License").
 * For more information see LICENSE or https://www.apache.org/licenses/LICENSE-2.0
 */

package meltc.sbt

import java.io.File

/** Reads and parses the `-- MELT GENERATED --` source-map comment block
  * that meltc appends to every generated `.scala` file.
  *
  * Block format:
  * {{{
  * /*
  *     -- MELT GENERATED --
  *     SOURCE: /abs/path/to/Counter.melt
  *     V3: <Base64-encoded Source Maps V3 JSON>
  *     -- MELT GENERATED --
  * */
  * }}}
  *
  * The `V3` value is a Base64-encoded JSON string produced by
  * `melt.codegen.SourceMapV3.generateBase64`.  The JSON has the form:
  * {{{
  * {"version":3,"sources":["/abs/path"],"names":[],"mappings":";;;AAGA;..."}
  * }}}
  */
object MeltGeneratedSource {

  /** Parsed metadata from the `-- MELT GENERATED --` block. */
  final case class Meta(
    sourcePath: String,
    lines:      IndexedSeq[(Int, Int, Int)] // (generatedLine, sourceLine, sourceColumn), ascending
  )

  private val BlockStart = "-- MELT GENERATED --"
  private val SourceKey  = "SOURCE:"
  private val V3Key      = "V3:"

  /** Attempts to read and parse the source-map block from `generatedFile`.
    * Returns `None` when the file does not exist, is unreadable, or contains
    * no `-- MELT GENERATED --` block (e.g. was compiled without a `sourcePath`).
    */
  def read(generatedFile: File): Option[Meta] = {
    if (!generatedFile.exists()) None
    else {
      val contentOpt =
        try {
          val src = scala.io.Source.fromFile(generatedFile, "UTF-8")
          try Some(src.mkString)
          finally src.close()
        } catch {
          case _: Exception => None
        }
      contentOpt.flatMap(parse)
    }
  }

  /** Parses the source-map block from a generated Scala source string.
    *
    * Searches from the tail to avoid matching a `-- MELT GENERATED --` string
    * inside user code.  Tries the V3 format first, falls back to the legacy
    * `LINES:` format for files generated by older meltc versions.
    */
  def parse(content: String): Option[Meta] = {
    val blockEnd   = content.lastIndexOf(BlockStart)
    val blockStart = if (blockEnd >= 0) content.lastIndexOf(BlockStart, blockEnd - 1) else -1

    if (blockEnd < 0 || blockStart < 0) None
    else {
      val block = content.substring(blockStart, blockEnd + BlockStart.length)

      val sourcePathOpt: Option[String] = {
        val idx = block.indexOf(SourceKey)
        if (idx < 0) None
        else {
          val afterKey = block.substring(idx + SourceKey.length)
          val end      = afterKey.indexOf('\n')
          Some(if (end < 0) afterKey.trim else afterKey.substring(0, end).trim)
        }
      }

      val lines: IndexedSeq[(Int, Int, Int)] = {
        val v3Idx = block.indexOf(V3Key)
        if (v3Idx < 0) IndexedSeq.empty
        else {
          val afterKey = block.substring(v3Idx + V3Key.length)
          val end      = afterKey.indexOf('\n')
          val b64      = if (end < 0) afterKey.trim else afterKey.substring(0, end).trim
          parseV3(b64).getOrElse(IndexedSeq.empty)
        }
      }

      sourcePathOpt.map(sourcePath => Meta(sourcePath, lines))
    }
  }

  /** Maps `generatedLine` to the corresponding `(sourceLine, sourceColumn)` using
    * nearest-neighbor lookup on the sorted `lines` array.
    *
    * Finds the largest entry whose generated-line is `<= generatedLine` and
    * returns its `(sourceLine, sourceColumn)`.  Returns `None` when `lines` is empty
    * or `generatedLine` is before the first entry.
    */
  def mapPosition(meta: Meta, generatedLine: Int): Option[(Int, Int)] = {
    val entries = meta.lines
    if (entries.isEmpty) None
    else {
      var lo = 0
      var hi = entries.length - 1
      var result: Option[(Int, Int, Int)] = None
      while (lo <= hi) {
        val mid = (lo + hi) >>> 1
        if (entries(mid)._1 <= generatedLine) {
          result = Some(entries(mid))
          lo     = mid + 1
        } else {
          hi = mid - 1
        }
      }
      result.map(e => (e._2, e._3))
    }
  }

  // ── V3 parsing ──────────────────────────────────────────────────────────────

  private def parseV3(base64: String): Option[IndexedSeq[(Int, Int, Int)]] = {
    try {
      val json     = new String(java.util.Base64.getDecoder.decode(base64), "UTF-8")
      val mappings = extractJsonString(json, "mappings").getOrElse("")
      Some(decodeMappings(mappings))
    } catch {
      case _: Exception => None
    }
  }

  /** Extracts the string value of a JSON key from a simple flat JSON object.
    * Works only for our controlled, single-line JSON format.
    */
  private def extractJsonString(json: String, key: String): Option[String] = {
    val needle = "\"" + key + "\":"
    val idx    = json.indexOf(needle)
    if (idx < 0) None
    else {
      val afterColon = json.substring(idx + needle.length).trim
      if (afterColon.startsWith("\"")) {
        val inner = afterColon.substring(1)
        val end   = findUnescapedQuote(inner)
        if (end < 0) None else Some(inner.substring(0, end))
      } else None
    }
  }

  private def findUnescapedQuote(s: String): Int = {
    var i       = 0
    var escaped = false
    while (i < s.length) {
      if (escaped) escaped = false
      else if (s(i) == '\\') escaped = true
      else if (s(i) == '"') return i
      i += 1
    }
    -1
  }

  // ── VLQ decoding ────────────────────────────────────────────────────────────

  private val B64 = {
    val a = new Array[Int](128)
    java.util.Arrays.fill(a, -1)
    val chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    chars.zipWithIndex.foreach { case (c, i) => a(c.toInt) = i }
    a
  }

  /** Decodes a Source Maps V3 `mappings` string into
    * `(generatedLine, sourceLine, sourceColumn)` triples (all 1-based).
    *
    * Only 4-field segments (with source position) are returned; 1-field segments
    * (generated column only) are silently skipped.
    */
  private def decodeMappings(mappings: String): IndexedSeq[(Int, Int, Int)] = {
    val result      = scala.collection.mutable.ArrayBuffer.empty[(Int, Int, Int)]
    var genLine     = 1
    var prevSrcLine = 0 // 0-based, cumulative
    var prevSrcCol  = 0 // 0-based, cumulative
    var i           = 0

    def readVlq(): Int = {
      var shift        = 0
      var value        = 0
      var continuation = true
      while (continuation && i < mappings.length) {
        val c = mappings(i).toInt
        if (c >= 128) { i += 1 } // skip non-ASCII (shouldn't occur)
        else {
          val digit = B64(c)
          i += 1
          if (digit < 0) { continuation = false }
          else {
            continuation = (digit & 0x20) != 0
            value |= (digit & 0x1f) << shift
            shift += 5
          }
        }
      }
      // sign bit is in LSB
      if ((value & 1) != 0) -(value >> 1) else value >> 1
    }

    while (i < mappings.length) {
      val ch = mappings(i)
      if (ch == ';') {
        genLine += 1
        i += 1
      } else if (ch == ',') {
        i += 1
      } else {
        // First field: generated column (we discard it, always 0 in our output)
        readVlq()
        // Check for more fields (4-field segment with source position)
        if (i < mappings.length && mappings(i) != ';' && mappings(i) != ',') {
          readVlq() // source file index delta (always 0 for us)
          val dlSrc = readVlq() // source line delta
          val dcSrc = readVlq() // source column delta
          prevSrcLine += dlSrc
          prevSrcCol += dcSrc
          result += ((genLine, prevSrcLine + 1, prevSrcCol + 1)) // back to 1-based
          // skip optional 5th field (name index)
          if (i < mappings.length && mappings(i) != ';' && mappings(i) != ',')
            readVlq()
        }
      }
    }

    result.toIndexedSeq
  }

}
