addSbtPlugin("io.github.takapi327" % "sbt-melt"                 % "0.1.0-SNAPSHOT")
addSbtPlugin("io.github.takapi327" % "sbt-meltkit"              % "0.1.0-SNAPSHOT")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"              % "1.22.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.4.0")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"             % "2.6.1")
